/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BhajansRouteImport } from './routes/bhajans'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AboutUsAnnakutMahotsavRouteImport } from './routes/about-us/annakut-mahotsav'
import { Route as AboutUsNewslettersRouteImport } from './routes/about-us/newsletters'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as BuildOurFutureSummerCampRouteImport } from './routes/build-our-future/summer-camp'
import { Route as BuildOurFutureVidyalayaRouteImport } from './routes/build-our-future/vidyalaya'
import { Route as BuildOurFutureVolunteerRouteImport } from './routes/build-our-future/volunteer'
import { Route as CalendarAnnualCalendarRouteImport } from './routes/calendar/annual-calendar'
import { Route as CalendarVaishnavMuhratRouteImport } from './routes/calendar/vaishnav-muhrat'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsSlugRouteImport } from './routes/events/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BhajansRoute = BhajansRouteImport.update({
  id: '/bhajans',
  path: '/bhajans',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AboutUsAnnakutMahotsavRoute = AboutUsAnnakutMahotsavRouteImport.update({
  id: '/about-us/annakut-mahotsav',
  path: '/about-us/annakut-mahotsav',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsNewslettersRoute = AboutUsNewslettersRouteImport.update({
  id: '/about-us/newsletters',
  path: '/about-us/newsletters',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildOurFutureSummerCampRoute =
  BuildOurFutureSummerCampRouteImport.update({
    id: '/build-our-future/summer-camp',
    path: '/build-our-future/summer-camp',
    getParentRoute: () => rootRouteImport,
  } as any)
const BuildOurFutureVidyalayaRoute = BuildOurFutureVidyalayaRouteImport.update({
  id: '/build-our-future/vidyalaya',
  path: '/build-our-future/vidyalaya',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildOurFutureVolunteerRoute = BuildOurFutureVolunteerRouteImport.update({
  id: '/build-our-future/volunteer',
  path: '/build-our-future/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarAnnualCalendarRoute = CalendarAnnualCalendarRouteImport.update({
  id: '/calendar/annual-calendar',
  path: '/calendar/annual-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarVaishnavMuhratRoute = CalendarVaishnavMuhratRouteImport.update({
  id: '/calendar/vaishnav-muhrat',
  path: '/calendar/vaishnav-muhrat',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bhajans': typeof BhajansRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/live': typeof LiveRoute
  '/resources': typeof ResourcesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/about-us/annakut-mahotsav': typeof AboutUsAnnakutMahotsavRoute
  '/about-us/newsletters': typeof AboutUsNewslettersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/build-our-future/summer-camp': typeof BuildOurFutureSummerCampRoute
  '/build-our-future/vidyalaya': typeof BuildOurFutureVidyalayaRoute
  '/build-our-future/volunteer': typeof BuildOurFutureVolunteerRoute
  '/calendar/annual-calendar': typeof CalendarAnnualCalendarRoute
  '/calendar/vaishnav-muhrat': typeof CalendarVaishnavMuhratRoute
  '/events/$slug': typeof EventsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bhajans': typeof BhajansRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/live': typeof LiveRoute
  '/resources': typeof ResourcesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/about-us/annakut-mahotsav': typeof AboutUsAnnakutMahotsavRoute
  '/about-us/newsletters': typeof AboutUsNewslettersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/build-our-future/summer-camp': typeof BuildOurFutureSummerCampRoute
  '/build-our-future/vidyalaya': typeof BuildOurFutureVidyalayaRoute
  '/build-our-future/volunteer': typeof BuildOurFutureVolunteerRoute
  '/calendar/annual-calendar': typeof CalendarAnnualCalendarRoute
  '/calendar/vaishnav-muhrat': typeof CalendarVaishnavMuhratRoute
  '/events/$slug': typeof EventsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bhajans': typeof BhajansRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/live': typeof LiveRoute
  '/resources': typeof ResourcesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/about-us/annakut-mahotsav': typeof AboutUsAnnakutMahotsavRoute
  '/about-us/newsletters': typeof AboutUsNewslettersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/build-our-future/summer-camp': typeof BuildOurFutureSummerCampRoute
  '/build-our-future/vidyalaya': typeof BuildOurFutureVidyalayaRoute
  '/build-our-future/volunteer': typeof BuildOurFutureVolunteerRoute
  '/calendar/annual-calendar': typeof CalendarAnnualCalendarRoute
  '/calendar/vaishnav-muhrat': typeof CalendarVaishnavMuhratRoute
  '/events/$slug': typeof EventsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/bhajans'
    | '/contact'
    | '/donate'
    | '/gallery'
    | '/live'
    | '/resources'
    | '/admin'
    | '/about-us/annakut-mahotsav'
    | '/about-us/newsletters'
    | '/blog/$slug'
    | '/build-our-future/summer-camp'
    | '/build-our-future/vidyalaya'
    | '/build-our-future/volunteer'
    | '/calendar/annual-calendar'
    | '/calendar/vaishnav-muhrat'
    | '/events/$slug'
    | '/blog/'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/bhajans'
    | '/contact'
    | '/donate'
    | '/gallery'
    | '/live'
    | '/resources'
    | '/admin'
    | '/about-us/annakut-mahotsav'
    | '/about-us/newsletters'
    | '/blog/$slug'
    | '/build-our-future/summer-camp'
    | '/build-our-future/vidyalaya'
    | '/build-our-future/volunteer'
    | '/calendar/annual-calendar'
    | '/calendar/vaishnav-muhrat'
    | '/events/$slug'
    | '/blog'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/bhajans'
    | '/contact'
    | '/donate'
    | '/gallery'
    | '/live'
    | '/resources'
    | '/_authenticated/admin'
    | '/about-us/annakut-mahotsav'
    | '/about-us/newsletters'
    | '/blog/$slug'
    | '/build-our-future/summer-camp'
    | '/build-our-future/vidyalaya'
    | '/build-our-future/volunteer'
    | '/calendar/annual-calendar'
    | '/calendar/vaishnav-muhrat'
    | '/events/$slug'
    | '/blog/'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BhajansRoute: typeof BhajansRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  GalleryRoute: typeof GalleryRoute
  LiveRoute: typeof LiveRoute
  ResourcesRoute: typeof ResourcesRoute
  AboutUsAnnakutMahotsavRoute: typeof AboutUsAnnakutMahotsavRoute
  AboutUsNewslettersRoute: typeof AboutUsNewslettersRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BuildOurFutureSummerCampRoute: typeof BuildOurFutureSummerCampRoute
  BuildOurFutureVidyalayaRoute: typeof BuildOurFutureVidyalayaRoute
  BuildOurFutureVolunteerRoute: typeof BuildOurFutureVolunteerRoute
  CalendarAnnualCalendarRoute: typeof CalendarAnnualCalendarRoute
  CalendarVaishnavMuhratRoute: typeof CalendarVaishnavMuhratRoute
  EventsSlugRoute: typeof EventsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bhajans': {
      id: '/bhajans'
      path: '/bhajans'
      fullPath: '/bhajans'
      preLoaderRoute: typeof BhajansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/about-us/annakut-mahotsav': {
      id: '/about-us/annakut-mahotsav'
      path: '/about-us/annakut-mahotsav'
      fullPath: '/about-us/annakut-mahotsav'
      preLoaderRoute: typeof AboutUsAnnakutMahotsavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/newsletters': {
      id: '/about-us/newsletters'
      path: '/about-us/newsletters'
      fullPath: '/about-us/newsletters'
      preLoaderRoute: typeof AboutUsNewslettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-our-future/summer-camp': {
      id: '/build-our-future/summer-camp'
      path: '/build-our-future/summer-camp'
      fullPath: '/build-our-future/summer-camp'
      preLoaderRoute: typeof BuildOurFutureSummerCampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-our-future/vidyalaya': {
      id: '/build-our-future/vidyalaya'
      path: '/build-our-future/vidyalaya'
      fullPath: '/build-our-future/vidyalaya'
      preLoaderRoute: typeof BuildOurFutureVidyalayaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-our-future/volunteer': {
      id: '/build-our-future/volunteer'
      path: '/build-our-future/volunteer'
      fullPath: '/build-our-future/volunteer'
      preLoaderRoute: typeof BuildOurFutureVolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/annual-calendar': {
      id: '/calendar/annual-calendar'
      path: '/calendar/annual-calendar'
      fullPath: '/calendar/annual-calendar'
      preLoaderRoute: typeof CalendarAnnualCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/vaishnav-muhrat': {
      id: '/calendar/vaishnav-muhrat'
      path: '/calendar/vaishnav-muhrat'
      fullPath: '/calendar/vaishnav-muhrat'
      preLoaderRoute: typeof CalendarVaishnavMuhratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BhajansRoute: BhajansRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  GalleryRoute: GalleryRoute,
  LiveRoute: LiveRoute,
  ResourcesRoute: ResourcesRoute,
  AboutUsAnnakutMahotsavRoute: AboutUsAnnakutMahotsavRoute,
  AboutUsNewslettersRoute: AboutUsNewslettersRoute,
  BlogSlugRoute: BlogSlugRoute,
  BuildOurFutureSummerCampRoute: BuildOurFutureSummerCampRoute,
  BuildOurFutureVidyalayaRoute: BuildOurFutureVidyalayaRoute,
  BuildOurFutureVolunteerRoute: BuildOurFutureVolunteerRoute,
  CalendarAnnualCalendarRoute: CalendarAnnualCalendarRoute,
  CalendarVaishnavMuhratRoute: CalendarVaishnavMuhratRoute,
  EventsSlugRoute: EventsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
